export const countryFlags = {
  en: "https://flagcdn.com/us.svg",
  gb: "https://flagcdn.com/gb.svg",
  fr: "https://flagcdn.com/fr.svg",
  de: "https://flagcdn.com/de.svg",
  it: "https://flagcdn.com/it.svg",
  ca: "https://flagcdn.com/ca.svg",
  jp: "https://flagcdn.com/jp.svg",
  cn: "https://flagcdn.com/cn.svg",
  in: "https://flagcdn.com/in.svg",
  br: "https://flagcdn.com/br.svg",
  ru: "https://flagcdn.com/ru.svg",
  za: "https://flagcdn.com/za.svg",
  au: "https://flagcdn.com/au.svg",
  mx: "https://flagcdn.com/mx.svg",
  kr: "https://flagcdn.com/kr.svg",
  ar: "https://flagcdn.com/ar.svg",
  sa: "https://flagcdn.com/sa.svg",
  tr: "https://flagcdn.com/tr.svg",
  eg: "https://flagcdn.com/eg.svg",
};
